config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "stories#new"

  resources :stories, :questions, :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :story
  belongs_to :user
end

app/models/story.rb
class Story < ApplicationRecord
  has_many :questions
  accepts_nested_attributes_for :questions
  belongs_to :user

  def self.process_questions(string)
    filtered_array = []
    questions = []

    quiz_array = string.strip.split(/(\d+)\./)

    quiz_array.each do |value|
      filtered_array << value if value[0] == ' '
    end

    filtered_array.each do |value|
      questions << value.split('A:')[0]
    end

    questions
  end

  def self.ask_ai(client, input)
    resp = client.completions(
      parameters: {
          model: "text-davinci-003",
          prompt: "Write a silly 1-paragraph story in simple english about #{input} with 3 reading comprehension questions in the following format \nQuestions\n1.QUESTION \nA: ANSWER \n2.QUESTION \nA: ANSWER \n3.QUESTION \nA: ANSWER",
          # prompt: "type a synonym for #{params[:input]}",
          max_tokens: 3000,
          temperature: 0.8
      })

    text_and_questions = resp["choices"][0]["text"].split('Questions')
  end 

  def self.get_json
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stories
  has_many :questions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :create_client
  before_action :get_story, only: [:show, :edit, :update]
  before_action :check_admin, only: [:destroy, :edit, :update]

  def index
    return if current_user.nil?

    if current_user.admin?
      @stories = Story.all
    else
      @stories = current_user.stories
    end 
  end

  def show
  end

  def new
    @story = Story.new

    unless params[:input].nil?
      text_and_questions = Story.ask_ai(@client, params[:input])
      @text = text_and_questions[0]
      @questions = Story.process_questions(text_and_questions[1])  
    else
      @text = "Type in a word and make a story!"
    end

    if defined?(@questions)
      3.times do |i|
        @story.questions.build(content: @questions[i])
      end    
    end 
  end

  def create
    @story = current_user.stories.new(story_params)

    if @story.save
      redirect_to @story
    else 
      render :new, status: :unprocessable_entity
    end 
  end

  def edit
  end

  def update
    if @story.update(story_params)
      redirect_to @story, notice: 'Story was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to root_path, notice: 'Story was successfully destroyed.'
  end

  private 

  def story_params
    params.require(:story).permit(:title, :content, questions_attributes: [:content, :answer, :user_id])
  end

  def create_client
    @client = OpenAI::Client.new
  end

  def get_story
    @story = Story.find(params[:id])
  end

  def check_admin 
    unless current_user.admin?
      redirect_to root_path, alert: "You don't have sufficient permissions to do this."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_admin

  def index
    @users = User.all
  end

  private 

  def check_admin
    unless current_user.admin?
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatgptHomework</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render '/shared/navbar' %>
    <%= render '/shared/navbar_mobile' %>
    <%= render '/shared/flash' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_navbar.html.erb
<nav id='navbar'>
  <%= link_to "AI STORY TiME", root_path, id: 'nav-title' %>
  <ul id='nav-links'>
    <%= link_to 'Home', root_path, class: 'nav-link' %>
    <%= link_to 'All Stories', stories_path, class: 'nav-link' %>
    <% if current_user.nil? %>
      <%= link_to 'Log in', new_user_session_path, class: 'nav-login' %>
    <% else  %>
      <%= link_to 'Log out', destroy_user_session_path, data: {turbo_method: :delete}, class: 'nav-login' %>
    <% end %>
  </ul>
</nav>

app/views/shared/_navbar_mobile.html.erb
<div data-controller='hello'> 
  <nav id='navbar-mobile'>
    <%= link_to "AI STORY TiME", root_path, id: 'nav-title' %>
    <div data-action='click->hello#toggle'><%= image_tag('hamburger.png', class: "ham-button") %></div>
  </nav>
  
  <ul id='ham-menu' class='nav-links-mobile inactive' data-hello-target='menu'>
    <%= link_to 'Home', root_path, class: 'nav-link' %>
    <%= link_to 'All Stories', stories_path, class: 'nav-link' %>
    <% if current_user.nil? %>
      <%= link_to 'Log in', new_user_session_path, class: 'nav-login' %>
    <% else  %>
      <%= link_to 'Log out', destroy_user_session_path, data: {turbo_method: :delete}, class: 'nav-login' %>
    <% end %>
  </ul>
</div>

app/views/stories/index.html.erb
<section class="main">
  <div class="box">
    <h1 class='title'>Past Stories!</h1>
    
    <ul class='story-list'>
      <% if current_user.nil? %>
        <li><%= link_to 'Log in', new_user_session_path, class: 'link' %> to see your stories!</li>
      <% else %>
        <% @stories.each do |story| %>
          <% if current_user.admin? %>
            <%= story.user.email %> - <%= link_to "Delete", story_path(story.id), data: {turbo_method: :delete} %>
          <% end %>

          <li><%= link_to story.title, story_path(story.id), class: 'story-name'%></li>

        <% end %>
      <% end %>
    </ul>
  </div>
</section>

app/views/stories/new.html.erb
<section class="main">
  <div class="box">
    <h1 class='title'>Let's make a story!</h1>

    <%= form_with url: new_story_path, method: :get, class: "" do |f| %>
        <%= f.text_field :input, placeholder: "Type one word!", class: "input" %>
    
        <%= f.submit "Create!", class: "button"%>
    <% end %>
    
    <div class="story-box"><p class='story'><%= @text %></p></div>
    
    <% if defined?(@questions) %>
      <div class="q-and-a">
        <ol class='questions'>
          <li class='question'><%= @questions[0] %></li>
          <li class='question'><%= @questions[1] %></li>
          <li class='question'><%= @questions[2] %></li>
          <li class='question'></li>
        </ol>
        
        <%= form_with model: @story, class: "answers" do |f| %>
          <%= f.fields_for :questions do |sf| %>
            <%= sf.hidden_field :content %>
            <% unless current_user.nil? %>
              <%= sf.hidden_field :user_id, value: current_user.id %>
            <% end %>
            <%= sf.text_field :answer, placeholder: 'Write your answer here!', class: "answer" %>
          <% end %>
        
          <%= f.hidden_field :title, value: params[:input]%>
          <%= f.hidden_field :content, value: @text %>

          <% if current_user.nil? %>
            <%= link_to "Sign in to submit!", new_user_session_path, class: 'button' %>
          <% else %>
            <%= f.submit "Submit Answers", class: "button"%>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <%#= image_tag('hamster.png', class: 'new-hamster') %>
</section>

<br><br>

<%= @json %>

app/views/stories/show.html.erb
<section class="main">
  <div class="box">
    <h1 class='title'><%= @story.title %></h1>
    <div class="story-box"><p class="story"><%= @story.content %></p></div>
    <ol>
      <% @story.questions.each do |q| %>
        <li><%= q.content %> - <%= q.answer %></li>
      <% end %>
    </ol>
  
    <%= link_to 'Home', stories_path, class: 'link' %>
  </div>
</section>

app/views/users/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br><br>
<br>

<h1>Users</h1>

<% @users.each do |user| %>
  <%= user.email %>
<% end %>